# Generated by Django 5.2.4 on 2025-08-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='tilte',
            new_name='title',
        ),
    ]
